// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.31.1
// source: metrics_disk_io.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiskIo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadBytes  int64  `protobuf:"varint,2,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes int64  `protobuf:"varint,3,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	ReadCount  int64  `protobuf:"varint,4,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	WriteCount int64  `protobuf:"varint,5,opt,name=write_count,json=writeCount,proto3" json:"write_count,omitempty"`
	ReadTime   int64  `protobuf:"varint,6,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	WriteTime  int64  `protobuf:"varint,7,opt,name=write_time,json=writeTime,proto3" json:"write_time,omitempty"`
}

func (x *DiskIo) Reset() {
	*x = DiskIo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_disk_io_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskIo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIo) ProtoMessage() {}

func (x *DiskIo) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_disk_io_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIo.ProtoReflect.Descriptor instead.
func (*DiskIo) Descriptor() ([]byte, []int) {
	return file_metrics_disk_io_proto_rawDescGZIP(), []int{0}
}

func (x *DiskIo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskIo) GetReadBytes() int64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskIo) GetWriteBytes() int64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *DiskIo) GetReadCount() int64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *DiskIo) GetWriteCount() int64 {
	if x != nil {
		return x.WriteCount
	}
	return 0
}

func (x *DiskIo) GetReadTime() int64 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

func (x *DiskIo) GetWriteTime() int64 {
	if x != nil {
		return x.WriteTime
	}
	return 0
}

type DiskIoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskIos []*DiskIo `protobuf:"bytes,1,rep,name=disk_ios,json=diskIos,proto3" json:"disk_ios,omitempty"`
}

func (x *DiskIoList) Reset() {
	*x = DiskIoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_disk_io_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskIoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIoList) ProtoMessage() {}

func (x *DiskIoList) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_disk_io_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIoList.ProtoReflect.Descriptor instead.
func (*DiskIoList) Descriptor() ([]byte, []int) {
	return file_metrics_disk_io_proto_rawDescGZIP(), []int{1}
}

func (x *DiskIoList) GetDiskIos() []*DiskIo {
	if x != nil {
		return x.DiskIos
	}
	return nil
}

var File_metrics_disk_io_proto protoreflect.FileDescriptor

var file_metrics_disk_io_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x69,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8,
	0x01, 0x0a, 0x06, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0a, 0x44, 0x69, 0x73,
	0x6b, 0x49, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6f, 0x52, 0x07, 0x64, 0x69, 0x73, 0x6b, 0x49, 0x6f,
	0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metrics_disk_io_proto_rawDescOnce sync.Once
	file_metrics_disk_io_proto_rawDescData = file_metrics_disk_io_proto_rawDesc
)

func file_metrics_disk_io_proto_rawDescGZIP() []byte {
	file_metrics_disk_io_proto_rawDescOnce.Do(func() {
		file_metrics_disk_io_proto_rawDescData = protoimpl.X.CompressGZIP(file_metrics_disk_io_proto_rawDescData)
	})
	return file_metrics_disk_io_proto_rawDescData
}

var file_metrics_disk_io_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_disk_io_proto_goTypes = []interface{}{
	(*DiskIo)(nil),     // 0: proto.DiskIo
	(*DiskIoList)(nil), // 1: proto.DiskIoList
}
var file_metrics_disk_io_proto_depIdxs = []int32{
	0, // 0: proto.DiskIoList.disk_ios:type_name -> proto.DiskIo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metrics_disk_io_proto_init() }
func file_metrics_disk_io_proto_init() {
	if File_metrics_disk_io_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metrics_disk_io_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiskIo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metrics_disk_io_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiskIoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metrics_disk_io_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_disk_io_proto_goTypes,
		DependencyIndexes: file_metrics_disk_io_proto_depIdxs,
		MessageInfos:      file_metrics_disk_io_proto_msgTypes,
	}.Build()
	File_metrics_disk_io_proto = out.File
	file_metrics_disk_io_proto_rawDesc = nil
	file_metrics_disk_io_proto_goTypes = nil
	file_metrics_disk_io_proto_depIdxs = nil
}
